INSERT INTO room (roomId, roomType, places, beds, roomDesc, price, created_at, updated_at)
VALUES
-- Solo Rooms
(1, 'Solo', 1, '1 single bed', "Enjoy a peaceful and comfortable stay in our cozy single rooms, designed for solo travelers. Each room features a comfortable bed, modern amenities, and a relaxing atmosphere, perfect for both work and rest. Whether you're here for business or leisure, our single rooms provide the ideal space for a restful night.", 800, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(2, 'Solo', 1, '1 single bed', "Enjoy a peaceful and comfortable stay in our cozy single rooms, designed for solo travelers. Each room features a comfortable bed, modern amenities, and a relaxing atmosphere, perfect for both work and rest. Whether you're here for business or leisure, our single rooms provide the ideal space for a restful night.", 800, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(3, 'Solo', 1, '1 single bed', "Enjoy a peaceful and comfortable stay in our cozy single rooms, designed for solo travelers. Each room features a comfortable bed, modern amenities, and a relaxing atmosphere, perfect for both work and rest. Whether you're here for business or leisure, our single rooms provide the ideal space for a restful night.", 800, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(4, 'Solo', 1, '1 single bed', "Enjoy a peaceful and comfortable stay in our cozy single rooms, designed for solo travelers. Each room features a comfortable bed, modern amenities, and a relaxing atmosphere, perfect for both work and rest. Whether you're here for business or leisure, our single rooms provide the ideal space for a restful night.", 800, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(5, 'Solo', 1, '1 single bed', "Enjoy a peaceful and comfortable stay in our cozy single rooms, designed for solo travelers. Each room features a comfortable bed, modern amenities, and a relaxing atmosphere, perfect for both work and rest. Whether you're here for business or leisure, our single rooms provide the ideal space for a restful night.", 800, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),

-- Double Rooms
(6, 'Double', 2, '1 double bed', "Relax and unwind in our spacious double rooms, ideal for couples or friends. With a cozy, comfortable bed, modern furnishings, and thoughtful amenities, these rooms offer the perfect setting for a restful stay. Whether you're enjoying a getaway or visiting for business, our double rooms provide the perfect blend of comfort and convenience.", 1200, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(7, 'Double', 2, '1 double bed', "Relax and unwind in our spacious double rooms, ideal for couples or friends. With a cozy, comfortable bed, modern furnishings, and thoughtful amenities, these rooms offer the perfect setting for a restful stay. Whether you're enjoying a getaway or visiting for business, our double rooms provide the perfect blend of comfort and convenience.", 1200, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(8, 'Double', 2, '1 double bed', "Relax and unwind in our spacious double rooms, ideal for couples or friends. With a cozy, comfortable bed, modern furnishings, and thoughtful amenities, these rooms offer the perfect setting for a restful stay. Whether you're enjoying a getaway or visiting for business, our double rooms provide the perfect blend of comfort and convenience.", 1200, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(9, 'Double', 2, '1 double bed', "Relax and unwind in our spacious double rooms, ideal for couples or friends. With a cozy, comfortable bed, modern furnishings, and thoughtful amenities, these rooms offer the perfect setting for a restful stay. Whether you're enjoying a getaway or visiting for business, our double rooms provide the perfect blend of comfort and convenience.", 1200, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(10, 'Double', 2, '1 double bed', "Relax and unwind in our spacious double rooms, ideal for couples or friends. With a cozy, comfortable bed, modern furnishings, and thoughtful amenities, these rooms offer the perfect setting for a restful stay. Whether you're enjoying a getaway or visiting for business, our double rooms provide the perfect blend of comfort and convenience.", 1200, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),

-- Twin Rooms
(11, 'Double', 2, '2 single beds', "Designed for flexibility and comfort, our twin rooms are perfect for friends or colleagues traveling together. Featuring two single beds, modern decor, and all the amenities you need, these rooms offer a relaxing and functional space to rest after a day of exploring or work. Enjoy a peaceful stay with everything you need right at your fingertips.", 1200, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(12, 'Double', 2, '2 single beds', "Designed for flexibility and comfort, our twin rooms are perfect for friends or colleagues traveling together. Featuring two single beds, modern decor, and all the amenities you need, these rooms offer a relaxing and functional space to rest after a day of exploring or work. Enjoy a peaceful stay with everything you need right at your fingertips.", 1200, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(13, 'Double', 2, '2 single beds', "Designed for flexibility and comfort, our twin rooms are perfect for friends or colleagues traveling together. Featuring two single beds, modern decor, and all the amenities you need, these rooms offer a relaxing and functional space to rest after a day of exploring or work. Enjoy a peaceful stay with everything you need right at your fingertips.", 1200, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(14, 'Double', 2, '2 single beds', "Designed for flexibility and comfort, our twin rooms are perfect for friends or colleagues traveling together. Featuring two single beds, modern decor, and all the amenities you need, these rooms offer a relaxing and functional space to rest after a day of exploring or work. Enjoy a peaceful stay with everything you need right at your fingertips.", 1200, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(15, 'Double', 2, '2 single beds', "Designed for flexibility and comfort, our twin rooms are perfect for friends or colleagues traveling together. Featuring two single beds, modern decor, and all the amenities you need, these rooms offer a relaxing and functional space to rest after a day of exploring or work. Enjoy a peaceful stay with everything you need right at your fingertips.", 1200, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),

-- Queen Rooms
(16, 'Queen', 2, '1 queen size bed', "Experience comfort and elegance in our queen rooms, featuring a spacious queen-size bed and stylish decor. Ideal for couples or solo travelers seeking extra space, these rooms are equipped with modern amenities to ensure a restful and enjoyable stay. Relax in a peaceful environment, designed with your comfort in mind.", 1800, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(17, 'Queen', 2, '1 queen size bed', "Experience comfort and elegance in our queen rooms, featuring a spacious queen-size bed and stylish decor. Ideal for couples or solo travelers seeking extra space, these rooms are equipped with modern amenities to ensure a restful and enjoyable stay. Relax in a peaceful environment, designed with your comfort in mind.", 1800, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(18, 'Queen', 2, '1 queen size bed', "Experience comfort and elegance in our queen rooms, featuring a spacious queen-size bed and stylish decor. Ideal for couples or solo travelers seeking extra space, these rooms are equipped with modern amenities to ensure a restful and enjoyable stay. Relax in a peaceful environment, designed with your comfort in mind.", 1800, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(19, 'Queen', 2, '1 queen size bed', "Experience comfort and elegance in our queen rooms, featuring a spacious queen-size bed and stylish decor. Ideal for couples or solo travelers seeking extra space, these rooms are equipped with modern amenities to ensure a restful and enjoyable stay. Relax in a peaceful environment, designed with your comfort in mind.", 1800, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(20, 'Queen', 2, '1 queen size bed', "Experience comfort and elegance in our queen rooms, featuring a spacious queen-size bed and stylish decor. Ideal for couples or solo travelers seeking extra space, these rooms are equipped with modern amenities to ensure a restful and enjoyable stay. Relax in a peaceful environment, designed with your comfort in mind.", 1800, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),

-- Suite Rooms
(21, 'Suite', 4, '1 queen and 1 king size bed', "Indulge in luxury and space with our suite rooms. Designed for ultimate comfort and relaxation, these spacious rooms feature a separate living area, a king-size bed, and premium amenities. Perfect for those seeking a more lavish experience, our suites offer a blend of style, elegance, and modern conveniences for an unforgettable stay.", 3000, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(22, 'Suite', 4, '1 queen and 1 king size bed', "Indulge in luxury and space with our suite rooms. Designed for ultimate comfort and relaxation, these spacious rooms feature a separate living area, a king-size bed, and premium amenities. Perfect for those seeking a more lavish experience, our suites offer a blend of style, elegance, and modern conveniences for an unforgettable stay.", 3000, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(23, 'Suite', 4, '1 queen and 1 king size bed', "Indulge in luxury and space with our suite rooms. Designed for ultimate comfort and relaxation, these spacious rooms feature a separate living area, a king-size bed, and premium amenities. Perfect for those seeking a more lavish experience, our suites offer a blend of style, elegance, and modern conveniences for an unforgettable stay.", 3000, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(24, 'Suite', 4, '1 queen and 1 king size bed', "Indulge in luxury and space with our suite rooms. Designed for ultimate comfort and relaxation, these spacious rooms feature a separate living area, a king-size bed, and premium amenities. Perfect for those seeking a more lavish experience, our suites offer a blend of style, elegance, and modern conveniences for an unforgettable stay.", 3000, '2024-11-05 15:28:55', '2024-11-13 11:33:15'),
(25, 'Suite', 4, '1 queen and 1 king size bed', "Indulge in luxury and space with our suite rooms. Designed for ultimate comfort and relaxation, these spacious rooms feature a separate living area, a king-size bed, and premium amenities. Perfect for those seeking a more lavish experience, our suites offer a blend of style, elegance, and modern conveniences for an unforgettable stay.", 3000, '2024-11-05 15:28:55', '2024-11-13 11:33:15');
